"""
Bit-N-Bulid Autonomous Setup Script

Run via: python scripts/setup.py
"""
import os
import sys
import subprocess
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

def write_env() -> str:
    print("[1/5] Detecting environment and creating .env...")
    spacetrack_user = os.environ.get("SPACETRACK_USER", "")
    spacetrack_pass = os.environ.get("SPACETRACK_PASS", "")

    use_celestrak = "true" if not (spacetrack_user and spacetrack_pass) else "false"

    db_url = os.environ.get("DATABASE_URL", "postgresql://bnb:bnb@localhost:5432/bitnbulid")

    env_content = f"""# Auto-generated by scripts/setup.py

DATABASE_URL={db_url}

SPACETRACK_USER={spacetrack_user}
SPACETRACK_PASS={spacetrack_pass}
USE_CELESTRAK={use_celestrak}

SCREENING_DISTANCE_KM=5.0
SCREENING_HORIZON_HOURS=24.0
PC_ALERT_THRESHOLD=1e-4
"""
    env_file = PROJECT_ROOT / ".env"
    env_file.write_text(env_content, encoding="utf-8")
    print(f"  -> Created .env file (USE_CELESTRAK={use_celestrak})")
    return db_url

def start_database(desired_db_url: str) -> str:
    print("[2/5] Initializing database backend...")
    actual_db_url = "sqlite:///data/bitnbulid.db"

    # Try Docker PostgreSQL if configured
    if "postgresql" in desired_db_url:
        docker_cmds = [["docker-compose", "up", "-d", "db"], ["docker", "compose", "up", "-d", "db"]]
        docker_success = False
        for cmd in docker_cmds:
            try:
                res = subprocess.run(cmd, cwd=PROJECT_ROOT, capture_output=True, text=True, timeout=15)
                if res.returncode == 0:
                    docker_success = True
                    break
            except Exception:
                continue

        if docker_success:
            # Check PostgreSQL connection
            try:
                import psycopg2
                conn = psycopg2.connect("postgresql://bnb:bnb@localhost:5432/bitnbulid", connect_timeout=3)
                conn.close()
                actual_db_url = desired_db_url
                print("  -> Successfully connected to PostgreSQL via Docker!")
            except Exception:
                print("  -> PostgreSQL unavailable or container starting up. Falling back to SQLite.")

    if actual_db_url.startswith("sqlite"):
        db_dir = PROJECT_ROOT / "data"
        db_dir.mkdir(exist_ok=True)
        print(f"  -> Using SQLite fallback database at {actual_db_url}")

    # Update .env with final selected database URL
    env_file = PROJECT_ROOT / ".env"
    if env_file.exists():
        content = env_file.read_text(encoding="utf-8")
        lines = content.splitlines()
        new_lines = []
        for l in lines:
            if l.startswith("DATABASE_URL="):
                new_lines.append(f"DATABASE_URL={actual_db_url}")
            else:
                new_lines.append(l)
        env_file.write_text("\n".join(new_lines) + "\n", encoding="utf-8")

    # Reload settings module environment
    os.environ["DATABASE_URL"] = actual_db_url
    return actual_db_url

def run_migrations():
    print("[3/5] Running Alembic database migrations...")
    try:
        from alembic.config import Config
        from alembic import command
        alembic_cfg = Config(str(PROJECT_ROOT / "alembic.ini"))
        alembic_cfg.set_main_option("script_location", str(PROJECT_ROOT / "alembic"))
        command.upgrade(alembic_cfg, "head")
        print("  -> Database migrations applied successfully.")
    except Exception as e:
        print(f"  -> Alembic API migration exception: {e}. Attempting direct table creation...")
        from bitnbulid.db.engine import engine
        from bitnbulid.db.models import Base
        Base.metadata.create_all(bind=engine)
        print("  -> SQLAlchemy tables created directly.")

def seed_catalog_data():
    print("[4/5] Ingesting TLE catalog data...")
    from scripts.seed_catalog import seed
    total = seed()
    print(f"  -> Catalog seed complete ({total} total objects in DB).")

def verify():
    print("[5/5] Verifying catalog screening...")
    from bitnbulid.agents.tracking import TrackingAgent
    tracker = TrackingAgent()
    events = tracker.step()
    print(f"  -> Screening verification complete ({len(events)} conjunction events found).")

def main():
    print("=== Bit-N-Bulid Autonomous Setup ===")
    initial_db_url = write_env()
    final_db_url = start_database(initial_db_url)
    run_migrations()
    seed_catalog_data()
    verify()
    print("\n=== Setup complete. Run: python -m bitnbulid.demo.mini_loop ===")

if __name__ == "__main__":
    main()
